# Generated by Django 2.1.7 on 2019-03-26 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='zip',
            field=models.CharField(blank=True, help_text='Zipcode', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Must be valid zipcode in formats 12345 or 12345-1234', regex='^(^[0-9]{5}(?:-[0-9]{4})?$|^$)')]),
        ),
    ]
