# Generated by Django 2.1.7 on 2019-03-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='address_line2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
